# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFiltrasia():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_filtrasia(self):
    self.driver.get("https://prokrasota.ru/")
    self.driver.find_element(By.LINK_TEXT, "Спрей для укладки волос").click()
    self.driver.find_element(By.ID, "sl_2").click()
    self.driver.find_element(By.ID, "arrFilter_P2_MAX").send_keys("1200")
    self.driver.find_element(By.ID, "set_filter").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sortFields > .dropDownSelected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".opened > .dropDownItem:nth-child(2)").click()
  
